on:
  push:

defaults:
  run:
    working-directory: ./source
    
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: source
        
    - name: source dir
      run: |
        pwd
        ls
        #cd source
        echo "::set-env name=FILELIST::$(printf '"%s" ' *.xml)"
        
    - uses: actions/checkout@v2
      with:
        ref: gh-pages 
        path: dest

    - name: dist dir
      run: |
        pwd
        ls
        cd ../dest
        pwd
        ls        
        

    - uses: docker://pandoc/core:2.9
      with:
        args: --from docbook --to html --output=../dest/index.html first_docbook_article.xml
            
            
    - name: list dest dir
      run: |
        pwd
        ls
        cd ../dest
        pwd
        ls   
