on:
  push:
    
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: source
        
    - name: source dir
      run: |
        cd ./source
        pwd
        ls
        #cd source
        echo "::set-env name=FILELIST::$(printf '"%s" ' *.xml)"
        
    - uses: actions/checkout@v2
      with:
        ref: gh-pages 
        path: dest

    - name: dist dir
      run: |
        pwd
        ls
        cd ./dest
        pwd
        ls        
        

    - uses: docker://pandoc/core:2.9
      with:
        args: --from docbook --to html --output=./dest/index.html ./source/first_docbook_article.xml
            
            
    - name: list dest dir
      run: |
        pwd
        ls
        cd ./dest
        pwd
        ls   
        
        
    - run: |
        pwd
        cd ./dest
        pwd
        ls
        git status
        git config --local user.email "action@github.com"        
        git config --local user.name "GitHub Action"
        git status
        git add .
        git commit -m "update docs"
        git push      
        
